server:
  port: 8081

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://dpg-d8f0u6ugvqtc738p8ed0-a.oregon-postgres.render.com:5432/chamados_ctlc
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql